TOPICS = [
    ("science", "Dark Matter", "the invisible architecture of the universe, what holds galaxies together"),
    ("science", "Entropy", "time's arrow, why everything falls apart and why that creates beauty"),
    ("science", "Quantum Entanglement", "two particles that dance together across any distance"),
    ("science", "The Placebo Effect", "the mind's power to reshape the body through belief alone"),
    ("science", "Mycelium Networks", "the internet under our feet, forests talking through fungi"),
    ("science", "Neutrinos", "ghost particles passing through everything, including us, every second"),
    ("science", "The Great Oxidation Event", "when poison became breath and changed Earth forever"),
    ("science", "Tardigrades", "indestructible microscopic creatures that survive space itself"),
    ("science", "The Double-Slit Experiment", "light that behaves differently when watched"),
    ("science", "Epigenetics", "how your grandparents' experiences echo in your DNA"),
    ("art", "The Color Blue", "why blue is the rarest in nature and the most desired in art"),
    ("art", "Cave Paintings", "the first hands on walls, reaching across 40000 years"),
    ("art", "The Readymade", "Duchamp's urinal and the question of what makes art art"),
    ("art", "Japanese Kintsugi", "repairing broken pottery with gold, making cracks beautiful"),
    ("art", "The Gaze in Painting", "who looks at whom and what that says about power"),
    ("art", "Art Forgery", "perfect copies that reveal more about authenticity than originals"),
    ("art", "The uncanny valley", "the moment when almost-human becomes deeply unsettling"),
    ("art", "Land Art", "art made from Earth itself that will outlive all of us"),
    ("art", "Glitch as Aesthetic", "beauty in broken signals, errors as expression"),
    ("art", "The White Cube Gallery", "how empty white rooms shape what we see and value"),
    ("engineering", "The Antikythera Mechanism", "a computer from 100 BC, found in a shipwreck"),
    ("engineering", "Ponte Vecchio", "a bridge that has been continuously built for 1000 years"),
    ("engineering", "The Large Hadron Collider", "the largest machine ever built by humans"),
    ("engineering", "Bridges That Bend", "suspension and the poetry of tensile strength"),
    ("engineering", "The Baghdad Battery", "a 2000-year-old jar that might have generated electricity"),
    ("engineering", "The Panama Canal", "a river of salt cutting a continent in half"),
    ("engineering", "Biomimicry", "engineering that copies nature's billion-year R&D"),
    ("engineering", "The Tacoma Narrows Bridge", "a bridge that danced itself to death in the wind"),
    ("engineering", "The International Space Station", "a floating city where countries collaborate"),
    ("engineering", "Roman Concrete", "why Roman harbors still stand while modern concrete crumbles"),
    ("inventions", "The Printing Press", "machines that made ideas immortal"),
    ("inventions", "The Double Helix Staircase", "Chambord Castle's staircase where two people never meet"),
    ("inventions", "The theremin", "an instrument played by touching nothing at all"),
    ("inventions", "The Gutenberg Bible", "the first mass-produced object of beauty"),
    ("inventions", "Zero", "the invention of nothing, the most dangerous idea in mathematics"),
    ("inventions", "The Camera Obscura", "a dark room that taught humans how to see"),
    ("inventions", "Velcro", "burrs on a dog's fur that became a global fastener"),
    ("inventions", "The Clock", "how measuring time changed human consciousness"),
    ("inventions", "The Plow", "a scratch in the earth that built civilization"),
    ("inventions", "The Alphabet", "2000 years of human thought compressed into 26 symbols"),
    ("literature", "The Library of Babel", "Borges' infinite library containing every possible book"),
    ("literature", "The Stream of Consciousness", "writing that mimics the river of thought itself"),
    ("literature", "Oulipo", "writers who imposed mathematical constraints to find freedom"),
    ("literature", "The Marginalia", "notes in the margins as a genre of its own"),
    ("literature", "Epistolary Novels", "stories told through letters people never meant to publish"),
    ("literature", "Concrete Poetry", "poems that become visual objects on the page"),
    ("literature", "Censored Books", "what happens when someone tries to burn words"),
    ("literature", "The Fairy Tale", "the darkest stories we tell children"),
    ("literature", "Palimpsests", "manuscripts scraped clean and written over, the past bleeding through"),
    ("literature", "Satire", "saying the unsayable by making people laugh first"),
    ("society", "The Panopticon", "a prison design where you never know if you are being watched"),
    ("society", "The Gift Economy", "societies built on giving, not trading"),
    ("society", "Shared Sanctuaries", "places where multiple religions pray under one roof"),
    ("society", "The Flâneur", "the art of wandering the city with no purpose but to observe"),
    ("society", "Ruins and Decay", "why we are drawn to places abandoned by humans"),
    ("society", "The Potlatch", "a ceremony where status comes from how much you give away"),
    ("society", "Letters to the Future", "time capsules and messages we will never read"),
    ("society", "The Commons", "shared resources managed by communities, not markets"),
    ("society", "Rituals of Strangers", "how cities make us intimate with people we will never know"),
    ("society", "Temporary Autonomous Zones", "moments of freedom outside the state's control"),
    ("fashion", "The Little Black Dress", "Chanel's revolution of simplicity"),
    ("fashion", "The Zoot Suit Riots", "when wearing a suit became a political act"),
    ("fashion", "Tattoo as Archive", "skin as a canvas for memory and identity"),
    ("fashion", "Kimono", "a garment that encodes Japan's aesthetics of time and space"),
    ("fashion", "Punk Fashion", "ripped clothes and safety pins as a middle finger to order"),
    ("fashion", "The Corset", "a cage that shaped bodies and sparked rebellion"),
    ("fashion", "Acubi Fashion", "minimalist non-conformity with sharp lines and soft edges"),
    ("fashion", "Sneaker Culture", "from sport utility to wearable art and status symbol"),
    ("fashion", "Uniqlos Life Wear", "clothing designed to disappear so life can appear"),
    ("fashion", "The Veil", "a piece of fabric that carries centuries of meaning and conflict"),
    ("pop-culture", "The GIF as Art Form", "looping images that capture emotions words cannot"),
    ("pop-culture", "K-pop and Global Fandom", "a music industry built on intimacy at scale"),
    ("pop-culture", "Meme Magic", "why a picture with text is the folk art of the internet age"),
    ("pop-culture", "Vaporwave", "a genre that mourns a future that never arrived"),
    ("pop-culture", "The Reality Show", "watching real people pretend to be real"),
    ("pop-culture", "Fanfiction", "millions of people rewriting stories because they love them"),
    ("pop-culture", "The 24-Hour News Cycle", "information turned into a constant background hum"),
    ("pop-culture", "ASMR", "millions of people find peace in the sound of whispering"),
    ("pop-culture", "Retro Gaming", "pixels and chiptunes as a nostalgia industry"),
    ("pop-culture", "Influencer Culture", "everyday people building empires from self-portraits"),
]
